[package]
name = "trident-syscall-stubs-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.1"
solana-sdk = "2.1"
solana-program-runtime = "2.1"
serde = { version = "1", default-features = false }
solana-bpf-loader-program = "2.1"
solana_rbpf = "*"
solana-timings = "2.1"