[package]
name = "turnstile"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "turnstile"
doctest = false

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.18.2"
trdelnik_program = { path = "../../../../crates/trdelnik_program" }

[dev-dependencies]
fehler = "1.0.0"
trdelnik = { path = "../../../../crates/trdelnik" }
program_client = { path = "../../program_client" }
