[[bin]]
name = "fuzz_0"
path = "fuzz_0/test_fuzz.rs"

[package]
name = "fuzz_tests"
version = "0.1.0"
description = "Created with Trident"
edition = "2021"

[dependencies]
honggfuzz = "0.5.56"
arbitrary = "1.3.0"
assert_matches = "1.4.0"

[dependencies.trident-client]
path = "../../../../../crates/client"

[dependencies.incorrect-ix-sequence-1]
path = "../../programs/incorrect-ix-sequence-1"
