# For the detailed description of the parameters, see: https://ackee.xyz/trident/docs/latest/features/trident-manifest/

[fuzz]
fuzzing_with_stats = true


[[fuzz.programs]]
address = "5e554BrmQN7a2nbKrSUUxP8PMbq55rMntnkoCPmwr3Aq"
program = "../target/deploy/maze.so"
 