[[bin]]
name = "fuzz_0"
path = "fuzz_0/test_fuzz.rs"

[package]
name = "fuzz_tests"
version = "0.1.0"
description = "Created with Trdelnik"
edition = "2021"

[dependencies]
honggfuzz = "0.5.55"
arbitrary = "1.3.0"
assert_matches = "1.4.0"

[dependencies.trdelnik-client]
path = "../../../../crates/client"
features = ["fuzzing"]

[dependencies.program_client]
path = "../../.program_client"

[dependencies.fuzzer]
path = "../../programs/fuzzer"
