on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

name: Test examples/escrow

env:
  SOLANA_CLI_VERSION: 1.16.6

jobs:
  turnstile:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: examples/escrow
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-solana/
      - uses: ./.github/actions/setup-rust/
        id: rust-setup
      - uses: Swatinem/rust-cache@v2
        name: Cache Rust and it's packages
        with:
          workspaces: "examples/turnstile -> target"
      - name: Install cargo packages
        run: |
          cargo install cargo-expand
          cargo install --force cargo-make
      - name: Cargo build
        run: cargo build
      - name: Prepare program client
        run: makers trdelnik build
      - name: Run trdelnik test
        run: makers trdelnik test
